### ISSUE TITLE
i restored it because it gave me problems, now I can't open file explorer

### ISSUE THREAD

**Issue by R3NdK01L** [windowtoolbox/powershell-windows-toolbox#10]

**Comment by computechnopro** [comment]
It destroyed the Start menu and Kodi and god knows what else and restoring doesn't do anything, I can't even reinstall windows 11 now without losing data😥

**Comment by Enubia** [comment]
although it's not the perfect solution, as a workaround you could use [files](https://www.microsoft.com/en-us/p/files-file-manager-for-windows/9nghp3dx8hdx?activetab=pivot:overviewtab) instead of explorer for now
